# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-01 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currencie', models.CharField(max_length=30, unique=True)),
                ('value_min', models.IntegerField(null=True)),
                ('value_max', models.IntegerField(null=True)),
            ],
        ),
    ]
