# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-01 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='value_max',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='value_min',
            field=models.FloatField(null=True),
        ),
    ]
