# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-01 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_auto_20171201_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='currency',
            new_name='currencie',
        ),
        migrations.AddField(
            model_name='alert',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
